In [1]:
import numpy as np
from scipy.stats import bernoulli
from bmm import BMM

The `BMM` class implements a [Expectation–maximization algorithm](https://en.wikipedia.org/wiki/Expectation%E2%80%93maximization_algorithm) for a [Mixture Model of Independent Bernoulli variables](http://www.vis.uky.edu/~cheung/courses/ee639_fall13/Notes/MixtureModel.pdf).

The model assumes that your data was generated from random variables $\textbf{v}$ like this:

$$p(\textbf{v}) = \sum_{h=1}^H q(h) \prod_{i=1}^D q(v_i|h)$$

from $H$ components, where each component $h$ defines a vector of probabilities $\textbf{q}_{h,i} = q(v_i=1|h)$.

### Sample Data

For example, let's assume the data is 3-dimensional and generated by 2 components:
$\textbf{q}_{1,\cdot} = (0.3,0.8,0.2)$, $\textbf{q}_{2,\cdot} = (0.9,0.1.0.6)$ 

In [2]:
q = np.array([[0.9, 0.1, 0.6],
              [0.3, 0.8, 0.2]])

With different probabilities $q(h)$ for the components:

In [3]:
q_h = np.array([0.2, 0.8])

Let's generated $N=10000$ samples from the the distribution $p(\textbf{v})$

In [4]:
h = np.random.choice(len(q_h), size=10000, p=q_h)
h[:10]

array([1, 1, 0, 1, 1, 1, 1, 1, 1, 0])

In [5]:
p = q[h, :]
p

array([[0.3, 0.8, 0.2],
       [0.3, 0.8, 0.2],
       [0.9, 0.1, 0.6],
       ...,
       [0.3, 0.8, 0.2],
       [0.3, 0.8, 0.2],
       [0.3, 0.8, 0.2]])

In [6]:
x = bernoulli.rvs(p)
x

array([[0, 1, 1],
       [0, 1, 0],
       [1, 0, 0],
       ...,
       [0, 1, 1],
       [0, 1, 0],
       [0, 1, 0]])

### Recovering the unknown components

The `BMM` classifier is able to recover the distribution $q(h)$ and $\textbf{q}^h_i$ from the data:

In [7]:
clf = BMM(n_comp=2, n_iter=1000)
clf = clf.fit(x)

In [8]:
clf.q.T

array([[0.28766763, 0.82802536, 0.17448613],
       [0.82408554, 0.20576621, 0.57600715]])

In [9]:
clf.qh.T

array([0.734475, 0.265525])